---
title: "Encoding and decoding selectivity in the human chemokine-GPCR interaction network"
---
This is my website

```{r echo=FALSE, results='hide', message=FALSE}
library(tidyverse)
library(plotly)
```

Now this is my plot
```{r echo=FALSE,message=FALSE}
data <- read_csv("data/bihler_2023_clean.csv")
q <- data %>%
  # filter(variant %in% c("WT-ctrl", "G551D-ctrl", "G551D", "F508del","F508del-ctrl", "I507del")) %>%
  # filter( (band_c_pct_wt_DMSO < 10) | (fsk_pct_wt_DMSO < 10)) %>%
    filter(!(is.na(trikafta_response))) %>%
  ggplot(aes(band_c_pct_wt_DMSO, fsk_pct_wt_DMSO, fill = trikafta_response, text  = variant)) +
  geom_point(shape = 21, colour = "black", size = 5, stroke = 0.5) +
  scale_fill_manual(values=c("red4", "grey70")) +
  # xlim(0,20) + 
  # ylim(0,20) + 
  geom_vline(xintercept = c(10), linetype=2) +
  geom_hline(yintercept = c(10), linetype=2) +
  labs(y = "conductance (mean, % WT)", x = "folding (mean, % WT)") +
  ggtitle("Variant-specific CFTR folding and conductance") +

  theme_minimal()
ggplotly(q)
```



Hello, Website!