---
title: "README"
author: "andrewbkleist"
date: "2023-09-18"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- README.md is generated from README.Rmd. Please edit that file -->


#### **Description of "Supplementary Table 1.xlsx" and related**
The table "Supplementary Table 1.xlsx" compiles evidence for chemokine-GPCR interactions from literature, including evidence supporting an interaction as well as evidence suggesting a lack of interaction. The table includes the following columns:  
- *"chemokine"*  
- *"chemokine_alternate_name"*  
- *"gpcr"*  
- *"PMID"*  
- *"author_date_journal"*  
- *"data_synopsis"* - direct quotations from text summarizing experimental data relating to interaction; for chemokines/GPCRs referenced in nonstandard names, the standardized chemokine/GPCR name is included in brackets  
- *"binding_kd_nm"* - radioligand (or related) binding assay Kd listed in nanomolar  
- *"binding_ec50_ic50_nm"* - radioligand (or related) binding assay EC50 or IC50 listed in nanomolar  
- *"signaling_ec50_ic50_nm"* - signaling assay (e.g. calcium flux, B-arrestin recruitment) EC50 or IC50 listed in nanomolar  
- *"chemotaxis_ec50_ic50_nm"* - chemotaxis EC50 or IC50 listed in nanomolar  
- *"chemotaxis_nax_nm"* - concentration at which maximal chemotaxis is achieved in nanonolar  
- *"data_comment"* - specifies signaling assay, binding assay, cells used, etc.  
- *"ligand_type"* - agonist, antagonist, or other based upon data presented in the associated source; ND = not determined  
- *"interaction_strength"* - assigned based on parameters from Kd, Ki, EC50, or IC50 from binding, signaling, or chemotaxis assay; assigned as "3" for parameter ≤100nM, "2" for parameter ≤1000nM, "1" for parameter >1000nM but with evidence of functional effect at high concentration, and "0" for no effect; for sources for which multiple parameters are listed, the parameter with the lowest value (i.e. most potent) is used to make the assignment; ND = not determined  
- *"evidence_grade"* - assigned based on type of evidence presented in source for/against listed interaction; assigned as "A" if a quantitative parameter was derived from concentration-response data (e.g. Kd, EC50, IC50, etc.), "B" if a semi-quantitative parameter was derived (e.g. dose of maximal chemotaxis), "C" if qualitative evidence is presented (e.g. single or multiple concentration point signaling assay without quantitative parameter), or "D" if indirect evidence is presented  
- *"other_comment"* - additional comments relating to the source, assignment of interaction strength/evidence grade  

See the Methods section associated with the manuscript for more information.  

Note that network-related analyses use "supplementary_table_1.csv" as an input, which was generated by saving "Supplementary Table 1.xlsx" as a .csv file without other modifications 